### ISSUE TITLE
devault-qt syncing progress bar is wrong?

### ISSUE THREAD

**Issue by kyeno** [devaultcrypto/devault#72]
This may be a missed report, but I have a feeling that the progress bar (at least on macOS) is wrong. It showed no progress at all for 12 days left, and just a pixel-length bar for 2 days left.
![Screen Shot 2019-04-08 at 9 21 19 PM](https://user-images.githubusercontent.com/1790957/55750821-7644b100-5a44-11e9-9251-2ad1f0b2d871.png)

**Comment by kyeno** [comment]
![Screen Shot 2019-04-17 at 5 38 46 PM 1](https://user-images.githubusercontent.com/1790957/56301256-be945b00-6137-11e9-9f38-2e761a4afe7e.png)
Not sure if this is an expected behavior. "Syncing Headers 100%" on the left, "Unknown. Syncing Headers" on the right.

**Comment by kyeno** [comment]
Another weird case. Progress bar alone seems about right, though the "Syncing Headers" below it is still quite weird; especially as it fluctuates/changes and changes with overall progress message as well. Let me know if this is desired behavior.
![Screen Shot 2019-04-19 at 5 36 23 AM](https://user-images.githubusercontent.com/1790957/56404140-4e83f300-6265-11e9-962e-746e0551c697.png)

**Comment by proteanx** [comment]
This is just because of our current "Target Spacing" setting of 2 seconds (should be 120 seconds) which has been set to enable us to rapidly stress test into the future. The progress bar progression should actually be a little off again now because of this too (was correct when I asked you to test after I applied the TxData checkpoint but over time with us not producing blocks in the networks expected time frame it starts to slip). Once there hasn't been a block within the expected time frame it switches to "Unknown. Syncing Headers" this behavior won't exist on mainnet (or even testnet once we switch to release settings).

**Comment by jonspock** [comment]
Closing this, please reopen if an issue after mainnet is running for a bit
